name: Figma tokens generator

on:
  workflow_dispatch:

  repository_dispatch:
    types: [figma_publish]

jobs:
  figma-tokens-generator:
    name: Generate Figma Tokens
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
            rm -f ./.npmrc
            ls -la
            yarn install

      - name: Run scripts
        env:
          FIGMA_PERSONAL_TOKEN: ${{ secrets.FIGMA_PERSONAL_TOKEN }}
          FIGMA_FILE_ID: ${{ github.event.client_payload.figmaFileId }}
        run:  
          yarn dev

      - name: Archive generated CSS files
        uses: actions/upload-artifact@v3
        with:
            name: generated-css-files
            path: ./generatedFiles/
            retention-days: 1

  create-figma-tokens-commit:
      name: Create Figma Tokens Commit
      needs: figma-tokens-generator
      runs-on: ubuntu-latest
      defaults:
          run:
              working-directory: target
      env:
          BRANCH_NAME: design/figma-update-autogenerated
      steps:
          - name: Checkout target project
            uses: actions/checkout@v3
            with:
                repository: even-MW/figma-tokens
                fetch-depth: 0
                path: ./target/

          - name: Create release branch
            run: |
                ls -ls
                git switch -c $BRANCH_NAME origin/$BRANCH_NAME

          - name: Create tokens directory
            run: |
                mkdir -p ./packages/tokens/

          - uses: actions/download-artifact@v3
            with:
                name: generated-css-files
                path: ./target/packages/tokens/

          - name: Display structure of downloaded files
            run: |
                cd ./packages/tokens/
                ls -R

          - name: Git merge with main
            run: |
                git config --global push.autoSetupRemote true
                git config user.name github-actions
                git config user.email github-actions@github.com
                git merge origin/main
            continue-on-error: false

          - name: Git commit
            run: |
                git add .
                git commit -am "Update Figma tokens from latest Figma design"
                git status
            continue-on-error: true

          - name: Git pull
            run: |
                git config pull.rebase false
                git pull origin $BRANCH_NAME
                git status
            continue-on-error: true

          - name: Git push  #          git pull origin $BRANCH_NAME
            run: |
                git push origin $BRANCH_NAME
                git status
